"""
Template Import Service

Imports a template (with full dependency graph) from a configured source Supabase
project into the current (target) project. See the approved plan for design notes.

Source DB is configured via env vars:
    SOURCE_SUPABASE_URL
    SOURCE_SUPABASE_SERVICE_KEY

The target DB is the project's default Supabase client.
"""
from __future__ import annotations

import logging
import os
import uuid
from typing import Any, Dict, List, Optional, Tuple

from fastapi import HTTPException
from supabase import create_client, Client

from services.supabase_service import supabase as target_client

logger = logging.getLogger(__name__)

# --- Columns we strip when copying rows between DBs (PKs + audit timestamps) ---
_TIMESTAMP_COLS = {"created_at", "updated_at"}

# Assembled-prompt columns on `templates` that must NOT be copied verbatim — they
# get regenerated by the assembly step on the target after insertion.
_TEMPLATE_ASSEMBLED_COLS = {
    "assembled_full_prompt",
    "prompt_assembled_at",
    "prompt_trigger_source",
    "prompt_assembly_hash",
    "assembled_schema_json",
    "schema_assembled_at",
    "schema_trigger_source",
    "schema_assembly_hash",
    "excluded_segment_codes",
    "assembled_audio_prompt",
    "audio_prompt_assembled_at",
    "audio_prompt_trigger_source",
    "audio_prompt_assembly_hash",
    "assembled_audio_schema_json",
    "audio_schema_assembled_at",
    "audio_schema_trigger_source",
    "audio_schema_assembly_hash",
    "assembled_text_emotion_prompt",
    "text_emotion_prompt_assembled_at",
    "text_emotion_prompt_trigger_source",
    "text_emotion_prompt_assembly_hash",
    "assembled_text_emotion_schema_json",
    "text_emotion_schema_assembled_at",
    "text_emotion_schema_trigger_source",
    "text_emotion_schema_assembly_hash",
    "assembled_combined_emotion_prompt",
    "assembled_combined_emotion_schema_json",
    # FK to system_prompt_configurations on source — meaningless on target until
    # reassembly resolves the active config via consultation_type_system_prompts.
    "system_prompt_config_id",
}


# ---------------------------------------------------------------------------
# Source client (lazy)
# ---------------------------------------------------------------------------

_source_client: Optional[Client] = None


def get_source_client() -> Client:
    """Lazily build a Supabase client pointed at the configured source project."""
    global _source_client
    if _source_client is not None:
        return _source_client

    url = os.getenv("SOURCE_SUPABASE_URL")
    key = os.getenv("SOURCE_SUPABASE_SERVICE_KEY")
    if not url or not key:
        raise HTTPException(
            status_code=500,
            detail=(
                "Source DB not configured (SOURCE_SUPABASE_URL / "
                "SOURCE_SUPABASE_SERVICE_KEY missing in backend .env)"
            ),
        )
    _source_client = create_client(url, key)
    return _source_client


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _strip(row: Dict[str, Any], drop: set) -> Dict[str, Any]:
    return {k: v for k, v in row.items() if k not in drop}


def _prep_insert(row: Dict[str, Any], drop: set) -> Dict[str, Any]:
    """Build an insert payload resilient to schema drift between source and target:
    drops the explicit cols AND any key whose value is None, so the target's
    column defaults can fire instead of forcing NULL into a NOT NULL column.
    """
    return {k: v for k, v in row.items() if k not in drop and v is not None}


def _segment_content_hash(row: Dict[str, Any]) -> str:
    """Hash the behavioral content of a segment_definitions row.

    `segment_code` is not unique on this table — multiple system-scoped rows can
    share a code with different prompt content. To bind an imported template to
    the correct target variant, we match by *content* (prompt_section_text +
    schema_definition_json) rather than by code alone.
    """
    import hashlib
    import json as _json

    prompt = row.get("prompt_section_text") or ""
    schema = row.get("schema_definition_json")
    schema_str = _json.dumps(schema, sort_keys=True, separators=(",", ":")) if schema is not None else ""
    return hashlib.md5(f"{prompt}\x00{schema_str}".encode("utf-8")).hexdigest()


def _fetch_one(client: Client, table: str, **eq) -> Optional[Dict[str, Any]]:
    query = client.table(table).select("*")
    for col, val in eq.items():
        query = query.eq(col, val)
    res = query.limit(1).execute()
    return res.data[0] if res.data else None


def _fetch_many(client: Client, table: str, **eq) -> List[Dict[str, Any]]:
    query = client.table(table).select("*")
    for col, val in eq.items():
        query = query.eq(col, val)
    res = query.execute()
    return res.data or []


# ---------------------------------------------------------------------------
# Public: list source templates (for the modal dropdown)
# ---------------------------------------------------------------------------


def list_source_templates() -> List[Dict[str, Any]]:
    """Return a slim list of templates on the source DB with consultation type info."""
    src = get_source_client()

    try:
        templates_res = (
            src.table("templates")
            .select("id, template_code, template_name, description, is_active, consultation_type_id, school_id, counsellor_id")
            .order("template_name")
            .execute()
        )
    except Exception as e:
        logger.error(f"[TEMPLATE_IMPORT] Failed to list source templates: {e}")
        raise HTTPException(status_code=502, detail="Could not reach source DB")

    rows = templates_res.data or []

    # Pull consultation_types in one go to label each template
    type_ids = sorted({r["consultation_type_id"] for r in rows if r.get("consultation_type_id")})
    type_map: Dict[str, Dict[str, str]] = {}
    if type_ids:
        types_res = (
            src.table("consultation_types")
            .select("id, type_code, type_name")
            .in_("id", type_ids)
            .execute()
        )
        for t in types_res.data or []:
            type_map[t["id"]] = {"type_code": t["type_code"], "type_name": t["type_name"]}

    out: List[Dict[str, Any]] = []
    for r in rows:
        t = type_map.get(r.get("consultation_type_id")) if r.get("consultation_type_id") else None
        out.append({
            "template_code": r["template_code"],
            "template_name": r["template_name"],
            "description": r.get("description"),
            "is_active": r.get("is_active"),
            "type_code": t["type_code"] if t else None,
            "type_name": t["type_name"] if t else None,
            "hospital_scoped": bool(r.get("school_id")),
            "doctor_scoped": bool(r.get("counsellor_id")),
        })
    return out


# ---------------------------------------------------------------------------
# Public: import one template by code from source → target
# ---------------------------------------------------------------------------


def import_template_from_source(source_template_code: str) -> Dict[str, Any]:
    """
    Full dependency-aware import of a single template from source → target.

    Order (all source reads first, then target writes):
      0. Read source graph
      1. Pre-flight on target (template_code collision, school_code remap feasible)
      2. Resolve or create consultation_type
      3. Resolve or create system prompt chain (config + components + junction)
      4. Resolve or create segment_definitions referenced by template + ct_segments
      5. Upsert consultation_type_segments rows
      6. Insert template + template_segments rows
      7. Re-assemble all prompt/schema variants on target
    """
    src = get_source_client()
    tgt = target_client

    counters: Dict[str, Any] = {
        "segment_definitions": 0,
        "consultation_type": False,
        "system_prompt_config": False,
        "system_prompt_components": 0,
        "consultation_type_segments": 0,
        "template_segments": 0,
        "hospital_remapped": False,
        "assembly_warnings": [],
    }

    # ------------------------------------------------------------------ 0
    src_template = _fetch_one(src, "templates", template_code=source_template_code)
    if not src_template:
        raise HTTPException(status_code=404, detail=f"Template '{source_template_code}' not found on source")

    src_consultation_type_id = src_template.get("consultation_type_id")
    if not src_consultation_type_id:
        raise HTTPException(status_code=400, detail="Source template has no consultation_type_id; cannot import")

    src_ct = _fetch_one(src, "consultation_types", id=src_consultation_type_id)
    if not src_ct:
        raise HTTPException(status_code=400, detail="Source consultation_type referenced by template is missing")

    src_template_segments = _fetch_many(src, "template_segments", template_id=src_template["id"])
    src_ct_segments = _fetch_many(src, "consultation_type_segments", consultation_type_id=src_consultation_type_id)

    # Collect every source segment_id we'll need
    src_segment_ids = sorted({
        s["segment_id"] for s in (src_template_segments + src_ct_segments)
        if s.get("segment_id")
    })
    src_segments: List[Dict[str, Any]] = []
    if src_segment_ids:
        sd_res = src.table("segment_definitions").select("*").in_("id", src_segment_ids).execute()
        src_segments = sd_res.data or []

    # Source system prompt chain: must find the active row for this ct on source
    src_ct_sysprompt = (
        src.table("consultation_type_system_prompts")
        .select("*")
        .eq("consultation_type_id", src_consultation_type_id)
        .eq("is_active", True)
        .limit(1)
        .execute()
    ).data
    src_ct_sysprompt = src_ct_sysprompt[0] if src_ct_sysprompt else None

    src_sys_config: Optional[Dict[str, Any]] = None
    src_sys_components: List[Dict[str, Any]] = []
    src_config_component_junctions: List[Dict[str, Any]] = []
    if src_ct_sysprompt:
        src_sys_config = _fetch_one(src, "system_prompt_configurations", id=src_ct_sysprompt["system_prompt_config_id"])
        if src_sys_config:
            src_config_component_junctions = _fetch_many(
                src, "system_prompt_config_components", config_id=src_sys_config["id"]
            )
            if src_config_component_junctions:
                comp_ids = [j["component_id"] for j in src_config_component_junctions]
                comps_res = src.table("system_prompt_components").select("*").in_("id", comp_ids).execute()
                src_sys_components = comps_res.data or []

    # Source school (for remap)
    src_school_code: Optional[str] = None
    if src_template.get("school_id"):
        src_school = _fetch_one(src, "schools", id=src_template["school_id"])
        if src_school and src_school.get("school_code"):
            src_school_code = src_school["school_code"]

    # ------------------------------------------------------------------ 1: pre-flight
    existing = tgt.table("templates").select("id, template_code").eq("template_code", source_template_code).limit(1).execute()
    if existing.data:
        raise HTTPException(status_code=409, detail=f"Template '{source_template_code}' already exists on target")

    target_school_id: Optional[str] = None
    if src_template.get("school_id"):
        if not src_school_code:
            raise HTTPException(
                status_code=400,
                detail="Source template's school has no school_code; cannot remap to target",
            )
        tgt_hosp = _fetch_one(tgt, "schools", school_code=src_school_code)
        if not tgt_hosp:
            raise HTTPException(
                status_code=400,
                detail=f"No school with code '{src_school_code}' exists on target",
            )
        target_school_id = tgt_hosp["id"]
        counters["hospital_remapped"] = True

    # ------------------------------------------------------------------ 2: consultation_type
    tgt_ct = _fetch_one(tgt, "consultation_types", type_code=src_ct["type_code"])
    if not tgt_ct:
        payload = _prep_insert(src_ct, drop=({"id"} | _TIMESTAMP_COLS))
        ins = tgt.table("consultation_types").insert(payload).execute()
        tgt_ct = ins.data[0]
        counters["consultation_type"] = True
        logger.info(f"[TEMPLATE_IMPORT] Created consultation_type '{src_ct['type_code']}' on target")
    target_consultation_type_id = tgt_ct["id"]

    # ------------------------------------------------------------------ 3: system prompt chain
    tgt_ct_sysprompt = (
        tgt.table("consultation_type_system_prompts")
        .select("*")
        .eq("consultation_type_id", target_consultation_type_id)
        .eq("is_active", True)
        .limit(1)
        .execute()
    ).data

    if not tgt_ct_sysprompt:
        # Target has no active sys prompt for this ct — copy from source
        if not src_ct_sysprompt or not src_sys_config:
            raise HTTPException(
                status_code=400,
                detail=(
                    f"Source DB is missing system prompt configuration for consultation type "
                    f"'{src_ct['type_code']}'; cannot import"
                ),
            )

        # Find / create target's system_prompt_configurations row by (config_code, config_version)
        tgt_config = (
            tgt.table("system_prompt_configurations")
            .select("*")
            .eq("config_code", src_sys_config["config_code"])
            .eq("config_version", src_sys_config.get("config_version") or "1.0.0")
            .limit(1)
            .execute()
        ).data
        tgt_config = tgt_config[0] if tgt_config else None

        if not tgt_config:
            # Strip FK to source's `inherits_from_id` — UUIDs don't translate.
            payload = _prep_insert(
                src_sys_config,
                drop=({"id", "inherits_from_id", "assembled_system_prompt", "assembled_at", "assembly_hash", "usage_count"} | _TIMESTAMP_COLS),
            )
            ins = tgt.table("system_prompt_configurations").insert(payload).execute()
            tgt_config = ins.data[0]
            counters["system_prompt_config"] = True
            logger.info(f"[TEMPLATE_IMPORT] Created system_prompt_configurations '{src_sys_config['config_code']}' on target")

        # Ensure every referenced component exists on target, build id map
        component_id_map: Dict[str, str] = {}  # src_component_id -> tgt_component_id
        for src_comp in src_sys_components:
            tgt_comp = (
                tgt.table("system_prompt_components")
                .select("*")
                .eq("component_code", src_comp["component_code"])
                .eq("content_version", src_comp.get("content_version") or "1.0.0")
                .limit(1)
                .execute()
            ).data
            if tgt_comp:
                component_id_map[src_comp["id"]] = tgt_comp[0]["id"]
                continue
            payload = _prep_insert(src_comp, drop=({"id"} | _TIMESTAMP_COLS))
            ins = tgt.table("system_prompt_components").insert(payload).execute()
            component_id_map[src_comp["id"]] = ins.data[0]["id"]
            counters["system_prompt_components"] += 1
            logger.info(f"[TEMPLATE_IMPORT] Created system_prompt_components '{src_comp['component_code']}' on target")

        # Junction rows on target. system_prompt_config_components has TWO unique
        # constraints: (config_id, component_id) and (config_id, display_order).
        # Skip on either match so we don't side-effect target's existing layout.
        for j in src_config_component_junctions:
            new_component_id = component_id_map.get(j["component_id"])
            if not new_component_id:
                continue
            exists = (
                tgt.table("system_prompt_config_components")
                .select("id, component_id, display_order")
                .eq("config_id", tgt_config["id"])
                .or_(f"component_id.eq.{new_component_id},display_order.eq.{j['display_order']}")
                .limit(1)
                .execute()
            ).data
            if exists:
                continue
            payload = _prep_insert(j, drop=({"id"} | _TIMESTAMP_COLS))
            payload["config_id"] = tgt_config["id"]
            payload["component_id"] = new_component_id
            tgt.table("system_prompt_config_components").insert(payload).execute()

        # consultation_type_system_prompts junction
        new_junction = {
            "consultation_type_id": target_consultation_type_id,
            "system_prompt_config_id": tgt_config["id"],
            "consultation_type_code": src_ct["type_code"],
            "config_code": tgt_config["config_code"],
            "is_active": True,
        }
        tgt.table("consultation_type_system_prompts").insert(new_junction).execute()
        logger.info(f"[TEMPLATE_IMPORT] Linked system_prompt_config '{tgt_config['config_code']}' to consultation_type '{src_ct['type_code']}'")

    # ------------------------------------------------------------------ 4: segment_definitions
    segment_id_map: Dict[str, str] = {}  # src_segment_id -> tgt_segment_id
    for src_seg in src_segments:
        # Look up ALL system-scoped target rows with this segment_code (segment_code is not unique).
        tgt_candidates = (
            tgt.table("segment_definitions")
            .select("*")
            .eq("segment_code", src_seg["segment_code"])
            .is_("counsellor_id", "null")
            .execute()
        ).data or []

        src_hash = _segment_content_hash(src_seg)
        matched = next((c for c in tgt_candidates if _segment_content_hash(c) == src_hash), None)

        if matched:
            segment_id_map[src_seg["id"]] = matched["id"]
            continue

        # No content match — insert source's row as a new system-scoped variant on target.
        # This preserves the source template's exact extraction behavior even when target
        # already has other variants of this segment_code with different content.
        payload = _prep_insert(
            src_seg,
            drop=({"id", "counsellor_id", "approved_by_admin_id"} | _TIMESTAMP_COLS),
        )
        ins = tgt.table("segment_definitions").insert(payload).execute()
        segment_id_map[src_seg["id"]] = ins.data[0]["id"]
        counters["segment_definitions"] += 1
        action = "created (no content match)" if tgt_candidates else "created (segment_code missing on target)"
        logger.info(
            f"[TEMPLATE_IMPORT] segment_definitions '{src_seg['segment_code']}' {action} on target "
            f"(target had {len(tgt_candidates)} other variant(s) with same code)"
        )

    # ------------------------------------------------------------------ 5: consultation_type_segments
    for src_cts in src_ct_segments:
        if not src_cts.get("segment_id"):
            continue
        new_segment_id = segment_id_map.get(src_cts["segment_id"])
        if not new_segment_id:
            continue
        # consultation_type_segments has TWO unique constraints:
        #   (consultation_type_id, segment_code) and (consultation_type_id, segment_id).
        # Skip if EITHER would conflict. Don't overwrite an existing consultation_type
        # default — the imported template overrides via its own template_segments.
        existing = (
            tgt.table("consultation_type_segments")
            .select("id, segment_id, segment_code")
            .eq("consultation_type_id", target_consultation_type_id)
            .or_(f"segment_id.eq.{new_segment_id},segment_code.eq.{src_cts['segment_code']}")
            .limit(1)
            .execute()
        ).data
        if existing:
            continue
        payload = _prep_insert(src_cts, drop=({"id"} | _TIMESTAMP_COLS))
        payload["consultation_type_id"] = target_consultation_type_id
        payload["segment_id"] = new_segment_id
        payload["consultation_type_name"] = src_ct["type_name"]
        tgt.table("consultation_type_segments").insert(payload).execute()
        counters["consultation_type_segments"] += 1

    # ------------------------------------------------------------------ 6: template + template_segments
    template_payload = _prep_insert(
        src_template,
        drop=({"id", "counsellor_id", "school_id", "consultation_type_id"} | _TIMESTAMP_COLS | _TEMPLATE_ASSEMBLED_COLS),
    )
    template_payload["consultation_type_id"] = target_consultation_type_id
    template_payload["school_id"] = target_school_id
    template_payload["counsellor_id"] = None
    template_payload["is_default"] = False  # never auto-default on target

    ins = tgt.table("templates").insert(template_payload).execute()
    new_template = ins.data[0]
    new_template_id = new_template["id"]
    logger.info(f"[TEMPLATE_IMPORT] Inserted template '{new_template['template_code']}' ({new_template_id}) on target")

    for src_ts in src_template_segments:
        if not src_ts.get("segment_id"):
            continue
        new_segment_id = segment_id_map.get(src_ts["segment_id"])
        if not new_segment_id:
            continue
        payload = _prep_insert(src_ts, drop=({"id"} | _TIMESTAMP_COLS))
        payload["template_id"] = new_template_id
        payload["segment_id"] = new_segment_id
        payload["template_name"] = new_template["template_name"]
        tgt.table("template_segments").insert(payload).execute()
        counters["template_segments"] += 1

    # ------------------------------------------------------------------ 7: re-assemble
    try:
        from services.template_assembly_service import (
            assemble_single_template_with_audio,
            assemble_template_text_emotion_prompt,
            assemble_template_text_emotion_schema,
            assemble_template_combined_emotion_prompt,
            assemble_template_combined_emotion_schema,
        )
        tpl_uuid = uuid.UUID(new_template_id)
        trigger = "import_from_source"

        try:
            assemble_single_template_with_audio(tpl_uuid, trigger)
        except Exception as e:
            counters["assembly_warnings"].append(f"prompt/schema/audio: {type(e).__name__}")
            logger.warning(f"[TEMPLATE_IMPORT] Standard+audio assembly failed: {e}")

        for fn, label in [
            (assemble_template_text_emotion_prompt, "text_emotion_prompt"),
            (assemble_template_text_emotion_schema, "text_emotion_schema"),
            (assemble_template_combined_emotion_prompt, "combined_emotion_prompt"),
            (assemble_template_combined_emotion_schema, "combined_emotion_schema"),
        ]:
            try:
                fn(tpl_uuid, trigger)
            except Exception as e:
                counters["assembly_warnings"].append(f"{label}: {type(e).__name__}")
                logger.warning(f"[TEMPLATE_IMPORT] {label} assembly skipped: {e}")
    except Exception as e:
        counters["assembly_warnings"].append(f"assembly_module: {type(e).__name__}")
        logger.error(f"[TEMPLATE_IMPORT] Could not run assembly step: {e}")

    return {
        "success": True,
        "template_id": new_template_id,
        "template_code": new_template["template_code"],
        "created": counters,
    }
